version: "3.8"

services:
#three containers 
  nginx: 
    image: "docker.io/nginx"
    ports: 
      - "80:80"
    networks:
      - frontend
    volumes: # binds nginx-conf
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf

  tomcat:
    image: dptweb:1.0 #using the image (Dockerfile) created with docker build
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
    volumes: #binding tomcat-users.xml 
      - ./services/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./services/tomcat/application.properties:/application.properties


  mySQL: 
    image: "docker.io/mysql"
    ports:
      - "3306:3306"
    volumes: #binding dump.sql database to the one in volume; dump.sql is the file that creates the table
      - ./services/mysql/dump.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: RootPass
      MYSQL_DATABASE: dataBase
      MYSQL_USER: User
      MYSQL_PASSWORD: PassWord
    networks:
      - backend
#separates networks
networks:
  frontend:
  backend:

